#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BerryPatch.Repository.Security
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="berrypatch_security")]
	public partial class VisitorDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public VisitorDataContext() : 
				base(global::BerryPatch.Repository.Properties.Settings.Default.berrypatch_securityConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public VisitorDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VisitorDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VisitorDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VisitorDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Visitor> Visitors
		{
			get
			{
				return this.GetTable<Visitor>();
			}
		}
	}
	
	[Table(Name="dbo.visitor")]
	public partial class Visitor
	{
		
		private string _email_address;
		
		private string _password;
		
		private string _first_name;
		
		private string _last_name;
		
		public Visitor()
		{
		}
		
		[Column(Name="email_address", Storage="_email_address", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string EmailAddress
		{
			get
			{
				return this._email_address;
			}
			set
			{
				if ((this._email_address != value))
				{
					this._email_address = value;
				}
			}
		}
		
		[Column(Name="password", Storage="_password", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this._password = value;
				}
			}
		}
		
		[Column(Name="first_name", Storage="_first_name", DbType="NChar(10)")]
		public string FirstName
		{
			get
			{
				return this._first_name;
			}
			set
			{
				if ((this._first_name != value))
				{
					this._first_name = value;
				}
			}
		}
		
		[Column(Name="last_name", Storage="_last_name", DbType="NChar(10)")]
		public string LastName
		{
			get
			{
				return this._last_name;
			}
			set
			{
				if ((this._last_name != value))
				{
					this._last_name = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
